# Generated by Django 3.2.3 on 2021-05-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieR', '0002_reviews_moviename'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='MovieReviewerName',
            field=models.CharField(default='Blade Runner', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='MovieName',
            field=models.CharField(max_length=255),
        ),
    ]
