# Generated by Django 3.2.3 on 2021-05-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieR', '0003_auto_20210528_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='Movieid',
        ),
    ]
